blank_issues_enabled: false
contact_links:
  - name: Optimism Help & Support
    url: https://github.com/ethereum-optimism/.github/blob/master/SUPPORT.md
    about: Please check our support guide for help with common issues 